GNU-CapstoneDesign-II/G-Learn-E-BE

- build.gradle
- src/main/java/gnu/capstone/G_Learn_E/domain/user/exception/UserNotFoundException.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/repository/UserRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/service/UserService.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/controller/AuthController.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/dto/response/EmailAuthCode.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/exception/AuthInvalidException.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/repository/email/EmailAuthCodeRepository.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/repository/email/InMemoryEmailAuthCodeRepository.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/repository/refresh/RefreshTokenRepository.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/service/AuthService.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/util/EmailValidator.java
- src/main/java/gnu/capstone/G_Learn_E/global/error/ControllerAdvice.java
- src/main/java/gnu/capstone/G_Learn_E/global/error/exception/client/AccessDeniedGroupException.java
- src/main/java/gnu/capstone/G_Learn_E/global/error/exception/client/AuthGroupException.java
- src/main/java/gnu/capstone/G_Learn_E/global/error/exception/client/InvalidGroupException.java
- src/main/java/gnu/capstone/G_Learn_E/global/error/exception/client/NotFoundGroupException.java
- src/main/java/gnu/capstone/G_Learn_E/global/error/exception/server/InternalServerErrorGroupException.java
- src/main/java/gnu/capstone/G_Learn_E/global/jwt/JwtAuthenticationFilter.java
- src/main/java/gnu/capstone/G_Learn_E/global/jwt/exception/JwtAuthException.java
- src/main/java/gnu/capstone/G_Learn_E/global/mail/EmailSender.java
- src/main/java/gnu/capstone/G_Learn_E/global/mail/exception/MailInternalException.java
- src/main/java/gnu/capstone/G_Learn_E/global/security/exception/SecurityAccessDeniedException.java
- src/main/java/gnu/capstone/G_Learn_E/global/security/exception/SecurityAuthException.java
- src/main/resources/application.yml
#17
이메일 인증 기능을 위한 전체적인 시스템을 설계하고 구현하였습니다.  
이 기능은 회원가입 시 이메일 유효성 검사 및 인증을 통해 사용자 검증을 강화하기 위해 도입되었습니다.  
다음과 같은 작업이 포함되어 있습니다:
- 이메일 인증 요청을 위한 컨트롤러 및 서비스 계층 구현  
- 인증 코드 생성, 저장, 중복 발급 방지 및 만료 처리  
- Gmail SMTP 연동을 통한 인증 코드 전송 기능 구현  
- 인증에 필요한 예외 처리 계층 및 메시지 일원화  
- `application.yml` 설정 추가 (메일 서버, 인증 코드 유효시간 및 도메인 제한)  
- 전반적인 예외 계층 구조 리팩토링 및 정리  
- `GET /api/auth/email-code?email={email}` 요청 시  
- 이메일 형식 및 도메인 유효성 검사  
- 사용자 존재 여부 검사 (이미 가입된 이메일은 인증 불가)  
- 기존 발급된 인증 코드 존재 시 중복 발급 제한  
- 유효한 이메일에 대해 인증 코드 생성 후 메일 발송  
- 인증 코드 저장 (임시 In-Memory 저장소)  
- 인증 메일 전송 실패 시 서버 예외 발생
- `InMemoryEmailAuthCodeRepository` 구현체 등록  
- 인증 코드는 ConcurrentHashMap에 저장되며, 타임스탬프 기반 만료 처리  
- 1분마다 만료된 코드 자동 제거 (스케줄러 활용)  
- 추후 Redis 등 외부 캐시 시스템으로 확장 가능하도록 인터페이스 기반 설계  
- 예외 그룹을 `client`, `server` 패키지로 분리  
- …
> [Feat #17] 이메일 인증 시스템 구현 및 인증 코드 발급 API 개발

- src/main/java/gnu/capstone/G_Learn_E/global/auth/controller/AuthController.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/dto/request/EmailAuthCodeVerify.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/dto/response/EmailAuthToken.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/exception/AuthInvalidException.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/repository/email/InMemoryEmailAuthCodeRepository.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/service/AuthService.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/util/EmailValidator.java
- src/main/java/gnu/capstone/G_Learn_E/global/jwt/JwtUtils.java
#17
이메일 인증 절차의 **2단계**인 "인증 코드 검증 API"를 구현하였습니다.  
이전 PR에서 구현된 이메일 인증 코드 발급 API에 이어, 사용자가 전달한 인증 코드의 유효성을 검증하고, 성공 시 이메일 인증 전용 토큰을 발급합니다.
- `POST /api/auth/email-code/verify`  
- 요청 바디:  
```json
{
"email": "example@gnu.ac.kr",
"authCode": "123456"
}
```
- 처리 로직:  
1. `EmailAuthCodeRepository.exists(email, authCode)`를 통해 유효성 확인  
2. 코드가 만료되었거나 불일치 시 예외 발생  
3. 성공 시 인증 코드를 삭제하여 재사용 방지  
4. `emailAuthToken`(JWT)을 생성하여 반환  
5. 토큰 유효시간은 `application.yml` 설정 기반
- `generateEmailAuthToken(email)` 메서드를 통해 이메일 인증 전용 토큰 발급  
- `emailAuthTokenExpiration` 필드를 `@Getter`로 노출하여 외부 접근 허용  
- 요청: `EmailAuthCodeVerify` record (email, authCode)  
- 응답: `EmailAuthToken` record (emailAuthToken)  
- 인증 코드가 유효하지 않을 때 사용자에게 전달할 예외 메시지 추가:
- `"유효하지 않은 인증 코드 입니다. 인증 코드를 재발급 해주세요."`
- 인증 코드가 일치하지 않을 경우, 해당 코드 즉시 삭제 …
> [Feat #17] 이메일 인증코드 검증 API

- src/main/java/gnu/capstone/G_Learn_E/domain/user/entity/User.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/exception/UserInvalidException.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/repository/UserRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/service/UserService.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/controller/AuthController.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/dto/request/LoginRequest.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/dto/request/SignupRequest.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/dto/response/TokenResponse.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/exception/AuthInvalidException.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/exception/AuthNotFoundException.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/repository/email/EmailAuthCodeRepository.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/repository/email/InMemoryEmailAuthCodeRepository.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/service/AuthService.java
- src/main/java/gnu/capstone/G_Learn_E/global/error/ControllerAdvice.java
- src/main/java/gnu/capstone/G_Learn_E/global/jwt/JwtAuthenticationFilter.java
- src/main/java/gnu/capstone/G_Learn_E/global/jwt/exception/JwtAuthException.java
- src/main/java/gnu/capstone/G_Learn_E/global/security/SecurityConfig.java
- src/main/java/gnu/capstone/G_Learn_E/global/security/exception/SecurityAccessDeniedException.java
- src/main/java/gnu/capstone/G_Learn_E/global/security/exception/handler/CustomAccessDeniedHandler.java
- src/main/java/gnu/capstone/G_Learn_E/global/security/exception/handler/CustomAuthenticationEntryPoint.java
- src/main/resources/application.yml
#17
---
이메일 인증을 기반으로 한 **로그인 및 회원가입 기능 전체 구현**을 완료하였습니다.  
이 PR에서는 다음의 핵심 로직을 포함하고 있습니다:
1. 이메일 인증이 완료된 사용자만 회원가입 가능하도록 설계  
2. 회원가입 시 이름, 닉네임, 이메일, 비밀번호를 포함하여 `User` 엔티티 저장  
3. 이메일 인증 토큰(JWT)을 통해 요청 사용자의 이메일을 식별  
4. 회원가입 후 AccessToken 및 RefreshToken 발급  
5. 예외 처리 강화 및 인증 관련 보안 로직 추가  
6. `EmailAuthCodeRepository` 역할 재정의 및 명확화  
7. 이메일, 비밀번호 기반 로그인 API 개발
8. 인증된 사용자에 대한 미인증 전용 URL 예외처리 추가
---
---
- `POST /api/auth/signup`
- 요청 바디:  
```json
{
"name": "홍길동",
"nickname": "gildong",
"email": "hong@gnu.ac.kr",
"password": "abc123!@#"
}
```
- 처리 로직:
1. 이메일 인증 토큰을 통해 요청한 이메일과 인증된 이메일 비교  
2. 이메일, 닉네임 중복 검사  
3. 비밀번호 암호화 후 유저 저장 (`BCryptPasswordEncoder`)  
4. AccessToken, RefreshToken 발급  
5. 응답에 두 토큰 포함 (`TokenResponse`)
- `JwtAuthenticationFilter`에서 토큰이 `email-auth` 타입일 경우  
- `/signup`, …
> [Feat #17] 이메일 인증 기반 로그인/회원가입 API 및 관련 예외/보안 로직 구현

- src/main/java/gnu/capstone/G_Learn_E/GLearnEApplication.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/College.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/Department.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/Subject.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/CollegeRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/DepartmentRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectRepository.java
- src/main/java/gnu/capstone/G_Learn_E/global/file_upload/controller/FileUploadController.java
- src/main/java/gnu/capstone/G_Learn_E/global/file_upload/service/FileUploadService.java
#25
퍼블릭 폴더 엔티티들에 Builder 패턴을 추가하고, 관련 Repository 메서드 개선 및 JSON 파일 업로드를 통한 퍼블릭 폴더 데이터 생성 기능을 구현하였습니다.
교과목 정보 json 파일은 노션 공유페이지에 업로드 해 두었습니다.
어떤 변경 사항이 있나요?
- **엔티티 개선**:  
- `College`, `Department`, `Subject` 엔티티에 Lombok의 `@Builder`를 추가하여 객체 생성의 편의성을 높였습니다.
- **Repository 개선**:  
- 퍼블릭 폴더 관련 Repository(`CollegeRepository`, `DepartmentRepository`, `SubjectRepository`)에 필요한 조회 및 저장 메서드를 추가하여 데이터 처리 효율성을 향상시켰습니다.
- **파일 업로드 기능 추가**:  
- `FileUploadController`와 `FileUploadService`를 새로 구현하여, JSON 파일을 업로드하면 비동기로 파일을 파싱 후 퍼블릭 폴더 데이터를 DB에 저장하도록 처리하였습니다.  
- JSON 파일 내 "colleges" 배열을 파싱하여, 각 대학(College), 학과(Department), 과목(Subject) 정보를 순차적으로 저장하며, 처리 완료 후 임시 파일을 삭제하는 로직을 포함하고 있습니다.
- **비동기 처리**:  
- `@Async` 어노테이션을 사용하여 파일 처리 작업을 비동기로 수행, 서버의 응답성을 유지합니다.
API 테스트
단과대
학과
과목
조회 API 테스트
> [FEAT #25] 경상대 시간표 Json 업로드

- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/SubjectResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/Subject.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/enums/SubjectGrade.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/service/PublicFolderService.java
- src/main/java/gnu/capstone/G_Learn_E/global/file_upload/service/FileUploadService.java
Closed #31
---
`Subject` 엔티티에 학년(`SubjectGrade`) 필드를 추가하고, 학년 및 교과목명 기준 정렬 로직을 적용했습니다. 또한 DTO 및 파일 업로드 로직에서도 해당 필드를 반영했습니다.
---
---
- `Subject` 엔티티에 `SubjectGrade` enum 필드 추가
- `SubjectResponse` DTO에 학년(grade) 추가 및 매핑 로직 수정
- `PublicFolderService` 내 교과목 정렬 로직 변경: 학년 순 → 교과목명 순
- 파일 업로드 서비스에서 학년 정보에 따라 `SubjectGrade` 변환 및 중복 방지 로직 추가
- 관련된 enum(`SubjectGrade`) 정의 및 정렬 기준 포함
---
---
> [Refactor #31] 교과목 엔티티에 학년 필드 추가

- src/main/java/gnu/capstone/G_Learn_E/domain/folder/entity/Folder.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/entity/FolderWorkbookId.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/entity/FolderWorkbookMap.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/repository/FolderRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/response/ProblemResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/entity/Problem.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/entity/User.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/service/UserService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/converter/WorkbookConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/Content.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/ProblemGenerateRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/QuestionTypes.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/ProblemGenerateResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/Workbook.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/enums/ExamType.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/enums/Semester.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
- src/main/java/gnu/capstone/G_Learn_E/global/fastapi/controller/FastApiController.java
- src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/request/AudioToStringRequest.java
- src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/request/FastApiProblemGenerateRequest.java
- src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/request/PdfToStringRequest.java
- src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/response/PdfToStringResponse.java
- src/main/java/gnu/capstone/G_Learn_E/global/fastapi/service/FastApiService.java
- src/main/resources/application.yml
#30  
---
- 유저 생성 시 개인 루트 디렉터리(`Folder`)를 자동 생성  
- 문제집 생성 시 해당 유저의 루트 디렉터리에 자동으로 매핑(`FolderWorkbookMap`)  
- 문제집 생성 API 개선 및 응답 포맷 확장  
- 문제 데이터 구조 및 변환 로직 구현 (`ProblemConverter`, `WorkbookConverter`)  
- FastAPI 요청/응답 분리 및 `PDF`, `오디오` 입력 처리 로직 구현  
---
---
- 유저 생성 시 개인 전용 루트 디렉터리 생성 (`UserService`)
- `FolderRepository.findByUserAndParentIsNull()`을 통해 루트 디렉터리 조회 가능
- 문제집 생성 시 자동으로 유저의 루트 폴더에 저장되도록 연동 (`FolderWorkbookMap`)
- 중간 엔티티 `FolderWorkbookMap`에 생성자 추가하여 깔끔하게 생성 가능하도록 개선
- `ProblemConverter`를 통한 문제 타입별 객체 변환 로직 구성
- `WorkbookConverter`를 통해 문제집 생성 시 일괄 변환 및 저장 처리
- 텍스트 + PDF + 오디오 입력 조합에 따라 요청 본문 생성
- `pdf-to-string`, `audio-to-string` 엔드포인트 연동 로직 작성
---
없음  
---
없음
> [Feat #30] 문제집 생성 API 개발

- src/main/java/gnu/capstone/G_Learn_E/domain/folder/controller/FolderController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/request/CreateFolderRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/request/MoveFolderRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/request/RenameFolderRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/response/FolderResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/response/FolderTreeResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/response/FolderWorkbookRemoveResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/response/SimpleFolderResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/entity/Folder.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/repository/FolderRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/repository/FolderWorkbookMapRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/service/FolderService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/Workbook.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
#38
개인 폴더링 시스템 기능 개발 완료: 폴더 생성, 조회, 트리 구조 조회, 이름 변경, 이동, 삭제 기능과 문제집 폴더 내 삭제 기능을 구현하였습니다.
어떤 변경 사항이 있나요?
- **폴더 CRUD API 개발**  
- 폴더 생성 (`POST /api/folder`)  
- 폴더 단일 조회 (`GET /api/folder/{id}`)  
- 폴더 트리 조회 (`GET /api/folder/folder-tree`)  
- 폴더 이름 변경 (`PATCH /api/folder/{id}/rename`)  
- 폴더 이동 (`PATCH /api/folder/{id}/move`)  
- 폴더 삭제 (`DELETE /api/folder/{id}`)  
- **문제집 폴더 내 삭제 API 개발**  
- `DELETE /api/folder/{folderId}/workbook/{workbookId}`  
- 문제집이 public에 업로드 된 경우, response로 isUploaded를 true로 반환
- **제약 조건 추가**  
- 루트 폴더 삭제 불가  
- 하위 폴더가 있거나 문제집이 있는 경우 삭제 불가  
- 순환 참조 방지를 위한 폴더 이동 제약  
- **응답 구조 설계 및 DTO 분리**  
- `FolderResponse`, `FolderTreeResponse`, `SimpleFolderResponse` 등 다수의 응답 DTO 도입  
- **서비스 계층 로직 정비**  
- LAZY / FETCH 전략을 고려한 폴더/문제집 조회  
- 사용자 검증 및 예외 처리 강화
(생략)
- 폴더 이동 시 …
> [Feat #38] 유저 폴더링 시스템

- src/main/java/gnu/capstone/G_Learn_E/domain/problem/controller/ProblemController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/response/ProblemResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/response/ProblemSolvePageResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/entity/Problem.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/repository/ProblemRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/service/ProblemService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/dto/response/SolveLogResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolveLog.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolvedWorkbook.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolvedWorkbookId.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/enums/SolvingStatus.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/repository/SolveLogRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/repository/SolvedWorkbookRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/converter/WorkbookConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
#41
- `ProblemController`: 문제집 내 문제 및 풀이 기록 조회 API(`/api/problem/workbook/{workbookId}`) 구현
- `ProblemConverter`: 문제 유형별 생성 로직에 `Workbook` 매핑 추가 및 `ProblemSolvePageResponse` 변환 메서드 구현
- `ProblemSolvePageResponse`: 문제와 사용자 풀이 기록을 포함하는 DTO 신규 작성
- `SolveLogService`: 사용자의 풀이 기록이 없을 시 자동 생성하는 로직 구현
- `ProblemResponse`: from 방식으로 생성 방식 통일 (`of` → `from`)
- `SolveLog`, `SolvedWorkbook`: 정답 여부, 풀이 상태 등 필드 추가 및 초기화 메서드 구성
- `WorkbookConverter`: 문제 생성 시 `Workbook` 정보 포함하여 `Problem` 생성
어떤 변경 사항이 있나요?
1. **문제 조회 API 구현**
- `GET /api/problem/workbook/{workbookId}` 엔드포인트 추가
- 인증된 사용자의 문제집 조회 시 문제 목록, 문제 풀이 기록, 정/오답 개수를 포함하여 응답
- 해당 API는 프론트엔드에서 문제 풀이 페이지 진입 시 사용될 수 있도록 설계됨
2. **문제 변환 로직 개선**
- 기존 문제 생성 메서드(`convertToMultipleProblem`, 등)에서 `Workbook` 객체를 추가 파라미터로 받아 문제에 연결되도록 수정
- …
> [Feat #41] 생성된 문제집 문제 조회 API

- src/main/java/gnu/capstone/G_Learn_E/domain/problem/controller/ProblemController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/controller/SolveLogController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/dto/request/SaveSolveLogRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/dto/request/SolveLogRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolveLog.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
#41
- `SolveLogController`에 사용자의 임시 풀이 로그 저장 API (`PATCH /solve-log/workbook/{workbookId}`)를 추가했습니다.
- 사용자 풀이 기록을 담는 `SaveSolveLogRequest`, `SolveLogRequest` DTO를 새로 생성했습니다.
- `SolveLogService`에 풀이 로그 갱신 로직 (`updateSolveLog`)을 추가했습니다.
- `ProblemConverter`에서 풀이 완료 전 정답 제출 여부도 반영되도록 수정했습니다.
어떤 변경 사항이 있나요?
1. **SolveLogController에 임시 저장 API 추가**  
- 사용자가 문제를 풀고 정답을 제출하지 않더라도 중간에 작성한 내용을 임시 저장할 수 있도록 API 엔드포인트를 `PATCH /api/solve-log/workbook/{workbookId}` 경로로 추가했습니다.  
- `@AuthenticationPrincipal`을 통해 사용자 인증 정보를 받아 해당 워크북과 연관된 풀이 기록을 업데이트합니다.
2. **SaveSolveLogRequest, SolveLogRequest DTO 생성**  
- 여러 문제에 대한 답안을 한 번에 받기 위해 `List<SolveLogRequest>` 형태의 `SaveSolveLogRequest`를 생성했습니다.  
- 각 문제별 `problemId`와 사용자가 입력한 `List<String>` 형태의 답안을 담는 `SolveLogRequest`를 정의했습니다.
3. **SolveLogService의 …
> [Feat #41] 문제 풀이 임시 저장 및 정답 제출 여부 response 개선

- src/main/java/gnu/capstone/G_Learn_E/domain/problem/controller/ProblemController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/converter/WorkbookConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookSolveResponse.java
#41
- 문제 풀이 페이지 로직을 `ProblemController`에서 `WorkbookController`로 이동시켰습니다.
- 기존 `ProblemSolvePageResponse`를 `WorkbookSolveResponse`로 이름 변경 및 경로 이동했습니다.
- `WorkbookConverter`에 문제 풀이 페이지 응답 변환 로직을 이관 및 통합했습니다.
- 관련 로직들을 `WorkbookController`, `WorkbookConverter` 중심으로 리팩토링했습니다.
어떤 변경 사항이 있나요?
1. **문제 풀이 페이지 API 도메인 변경**  
- 기존에 `ProblemController`에 위치하던 문제 풀이 페이지 로드 API(`/api/problem/workbook/{workbookId}`)를 `WorkbookController`로 이동하였고, 새로운 경로는 `/api/workbook/{workbookId}/solve`입니다.  
- 문제 풀이의 도메인 상 위치가 문제(`Problem`)가 아닌 문제집(`Workbook`)에 더 적합하다고 판단되어 이동 처리하였습니다.
2. **응답 DTO 클래스 및 이름 변경**  
- 기존 `ProblemSolvePageResponse` 클래스는 `WorkbookSolveResponse`로 변경되었습니다.  
- 문제풀이와 관련된 데이터 구조도 그에 맞춰 네이밍 수정이 이루어졌습니다.
3. **문제 변환 로직을 WorkbookConverter로 통합**  
- 문제 리스트 및 풀이 기록을 통합해서 가공하던 로직은 기존에 …
> [Refactor #41] 문제 풀이 페이지 API 도메인 변경

- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/controller/SolveLogController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
#41
- 사용자 풀이 기록 전체 삭제를 위한 API(`/api/solve-log/workbook/{workbookId}`)를 `DELETE` 방식으로 추가하였습니다.
- `SolveLogService`에 문제 풀이 로그 및 문제집 풀이 상태를 초기화하는 `deleteAllSolveLog` 메서드를 구현했습니다.
어떤 변경 사항이 있나요?
1. **풀이 기록 초기화 API 추가**  
- 사용자가 특정 문제집의 풀이를 완전히 초기화할 수 있도록 `DELETE /api/solve-log/workbook/{workbookId}` API를 추가했습니다.  
- 요청 시, 해당 워크북에 대한 사용자의 풀이 기록(`SolveLog`)과 전체 문제집 풀이 상태(`SolvedWorkbook`)가 모두 삭제됩니다.
2. **SolveLogService에 초기화 로직 구현**  
- `deleteAllSolveLog(SolvedWorkbook solvedWorkbook)` 메서드를 새로 정의하여,  
(1) 워크북에 대한 개별 문제 풀이 로그들을 삭제하고  
(2) 최종적으로 문제집 단위의 풀이 상태 객체도 삭제합니다.  
- 트랜잭션 처리를 통해 안정적으로 전체 초기화가 수행되도록 구성했습니다.
없음
- 향후 특정 문제만 선택적으로 초기화하는 기능도 고려할 수 있을지, 현재 구조로 확장이 용이한지 검토 부탁드립니다.
- 삭제 시의 사용자 경험(예: "정말 초기화하시겠습니까?" 같은 프론트 경고창 등)도 함께 고려되면 좋겠습니다.
> [Feat #41] 문제 풀이 기록 초기화 API 추가

- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolveLog.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolvedWorkbook.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/GradeWorkbookResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/repository/WorkbookRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
#41
- 문제집 풀이를 채점하는 API(`/api/workbook/{workbookId}/grade`)를 추가했습니다.
- 객관식, OX는 로컬에서 즉시 채점, 빈칸/서술형 문제는 FastAPI를 활용한 비동기 채점 방식으로 구현했습니다.
- 채점 후 전체 정오답 개수를 포함한 결과(`GradeWorkbookResponse`)를 반환합니다.
- 관련된 서비스 메서드 및 DTO 클래스, 레포지토리 확장을 포함합니다.
어떤 변경 사항이 있나요?
1. **채점 API 엔드포인트 추가**  
- `POST /api/workbook/{workbookId}/grade`로 사용자가 제출한 풀이 기록을 채점합니다.  
- 요청 시 먼저 기존 풀이 로그를 갱신하고, 이어서 전체 문제를 채점하는 방식입니다.
2. **SolveLogService 내부 채점 로직 구현**  
- 객관식, OX 문제는 로컬에서 정답 리스트와 제출 리스트를 직접 비교해 채점합니다.  
- 빈칸(`BLANK`)과 서술형(`DESCRIPTIVE`)은 각각 FastAPI에 비동기로 요청하여 채점 결과를 받아옵니다.  
- 모든 채점 결과를 기존 풀이 로그(`SolveLog`)에 반영하고, `SolvedWorkbook`의 상태를 `COMPLETED`로 변경합니다.
3. **GradeWorkbookResponse 응답 DTO 추가**  
- 채점 결과로 정답 개수와 오답 개수를 담은 `GradeWorkbookResponse`를 반환합니다.
4. **WorkbookRepository, WorkbookService 확장**  
- 문제집과 함께 문제 리스트를 …
> [Feat #41] 문제 풀이 채점 API 추가

- src/main/java/gnu/capstone/G_Learn_E/GLearnEApplication.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/response/ProblemResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/entity/Problem.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/entity/ProblemWorkbookMap.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/repository/ProblemRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/repository/ProblemWorkbookMapRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/service/ProblemService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/converter/WorkbookConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/Workbook.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/repository/WorkbookRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
- src/main/java/gnu/capstone/G_Learn_E/global/admin/AdminController.java
- src/main/java/gnu/capstone/G_Learn_E/global/admin/dto/CleanupResult.java
- src/main/java/gnu/capstone/G_Learn_E/global/scheduler/OrphanCleanupScheduler.java
#52
- `Problem`과 `Workbook`의 관계를 `ProblemWorkbookMap`을 통한 N:M 매핑으로 리팩토링했습니다.
- 고아 문제(어떤 문제집에도 속하지 않는 문제)와 고아 문제집을 정리하는 스케쥴러 및 관리자 API를 추가했습니다.
- 기존 문제 생성, 조회, 풀이 로직들을 새 매핑 구조에 맞게 수정했습니다.
- 각 도메인(`Problem`, `Workbook`, `SolveLog`, 등) 관련 Repository, Service, Converter 코드들을 리팩토링했습니다.
어떤 변경 사항이 있나요?
1. **Problem-Workbook 매핑 구조 변경**
- `ProblemWorkbookMap` 엔티티를 도입하여 문제와 문제집 간 다대다(N:M) 관계를 관리합니다.
- 문제 번호(`problemNumber`)를 매핑 테이블에서 관리하여 문제 재정렬 및 복수 매핑을 가능하게 했습니다.
2. **Orphan Cleanup 기능 추가**
- 고아 워크북(폴더와 과목에 속하지 않은 워크북)과 고아 문제(어떤 문제집에도 포함되지 않은 문제)를 정리하는 스케쥴러(`OrphanCleanupScheduler`)를 구현했습니다.
- `/api/admin/orphans` 엔드포인트를 통해 관리자가 즉시 정리할 수 있도록 API를 추가했습니다.
3. **Service 및 Repository 리팩토링**
- `WorkbookService`, `SolveLogService` 등에서 기존 문제 조회 및 채점 로직을 `ProblemWorkbookMap` 기반으로 수정했습니다.
- …
> [Refactor #52] 문제, 문제집 N:M 매핑 리팩토링 및 고아 엔티티 정리 기능 추가

- src/main/java/gnu/capstone/G_Learn_E/domain/folder/repository/FolderRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/service/FolderService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/request/ProblemRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/enums/ProblemType.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/repository/ProblemRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/problem/service/ProblemService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/controller/PublicFolderController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/WorkbookResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/SubjectWorkbookId.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/SubjectWorkbookMap.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/DepartmentRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectWorkbookMapRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/service/PublicFolderService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/controller/SolveLogController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/WorkbookMergeRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/WorkbookUpload.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/WorkbookUploadList.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookDownloadResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookMergePageResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookUploadResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/Workbook.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/repository/WorkbookRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
#51
- 공개 문제집 업로드/다운로드 기능 추가
- 문제집 병합 기능 및 페이지 API 추가
- SolveLog 접근 권한 검증 로직 추가
- ProblemRequest 및 Converter 로직 구현
- Workbook 도메인에 author 필드 추가 및 관련 로직 보완
- PublicFolderService 기능 강화 (권한 검증, 상세 조회 등)
- 불필요한 로그 제거 및 코드 리팩토링
어떤 변경 사항이 있나요?
1. **공개 문제집 업로드/다운로드 기능 추가**
- 개인 문제집을 공개폴더(Subject)에 업로드하는 API(`POST /workbooks/{id}/upload`) 구현.
- 공개 문제집을 개인 폴더로 다운로드하는 기능(`POST /workbooks/{id}/download`) 구현.
- Workbook 엔티티에 `author` 및 `isUploaded` 필드 추가, 관련 로직 반영.
2. **문제집 병합 기능 추가**
- 여러 문제집을 하나로 병합할 수 있는 병합 페이지 로딩 API(`GET /workbooks/merge`) 및 병합 수행 API(`POST /workbooks/merge`) 구현.
- 병합시 기존 문제를 재사용하거나 새로 생성해 저장하도록 처리.
3. **SolveLog 접근 권한 강화**
- SolveLog 관련 API 접근 시 `개인폴더 또는 공개폴더에 속한 문제집`에 대해서만 접근 가능하도록 검증 추가.
4. **ProblemRequest 및 Converter 로직 구현**
- 문제 유형(MULTIPLE, OX, BLANK, DESCRIPTIVE)에 따라 문제 …
> [Feat #51] 공개 문제집 업로드/다운로드 및 병합 기능 구현

- build.gradle
- src/main/java/gnu/capstone/G_Learn_E/domain/folder/controller/FolderController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/notification/controller/NotificationController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/controller/PublicFolderController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/controller/SolveLogController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/controller/UserController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
- src/main/java/gnu/capstone/G_Learn_E/global/admin/AdminController.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/controller/AuthController.java
- src/main/java/gnu/capstone/G_Learn_E/global/config/SwaggerConfig.java
- src/main/java/gnu/capstone/G_Learn_E/global/file_upload/controller/FileUploadController.java
- Swagger(OpenAPI) 라이브러리 의존성 추가 (`build.gradle`)
- 전 API 컨트롤러에 Swagger 어노테이션 추가 (`@Tag`, `@Operation`)
- API 문서화를 위한 준비 작업 완료
어떤 변경 사항이 있나요?
1. `build.gradle` 파일에 Swagger(OpenAPI)를 사용하기 위한 라이브러리 `springdoc-openapi-starter-webmvc-ui:2.1.0`을 추가하였습니다. 이를 통해 자동 API 문서화가 가능합니다.
2. `FolderController`, `NotificationController`, `PublicFolderController`, `SolveLogController`, `UserController`, `WorkbookController`, `AdminController` 등 주요 API 컨트롤러에 Swagger 문서화를 위한 어노테이션을 추가하였습니다.
- 각 클래스 상단에 `@Tag(name = "...")` 어노테이션을 추가하여 해당 컨트롤러의 기능을 명시하였습니다.
- 각 API 메서드에 `@Operation(summary = "...", description = "...")`을 추가하여 Swagger UI에서 API 설명이 명확히 보이도록 했습니다.
3. 해당 작업을 통해 Swagger UI 접속 시 모든 API에 대한 명확한 분류 및 설명을 확인할 수 있으며, 프론트엔드 개발자 및 외부 협업자들이 API를 쉽게 테스트하고 이해할 수 있도록 하였습니다.
플젝 실행하고 …
> [Feat #55] Swagger 세팅

- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/controller/DevPublicFolderController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/controller/PublicFolderController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/request/UpdateCollege.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/College.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/CollegeRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/service/DevPublicFolderService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/service/PublicFolderService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/controller/UserController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/request/AffiliationUpdateRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/response/UserInfoResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/entity/User.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/service/UserService.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/controller/AuthController.java
- src/main/java/gnu/capstone/G_Learn_E/global/auth/dto/request/SignupRequest.java
#58
- 회원가입 시 단과대 및 학과 정보 기입 기능 추가
- 유저 소속 정보(단과대, 학과) 업데이트 API 추가
- 유저 조회 시 소속 정보 포함 응답
- 단과대 여부 필터링 조회 API 구현
- 단과대의 isCollege 필드 업데이트 API 구현
- 관련 엔티티 및 DTO 필드/로직 추가
어떤 변경 사항이 있나요?
1. **회원가입 시 단과대 및 학과 정보 기입 기능 추가**
- `SignupRequest` DTO에 `collegeId`, `departmentId` 필드 추가
- `AuthController`에서 `UserService.save()` 호출 시 단과대/학과 엔티티를 함께 저장하도록 수정
2. **유저 소속 정보 업데이트 API 추가**
- `UserController`에 `/user/affiliation` PATCH API 추가
- `UserService`에 `updateAffiliation()` 로직 구현
- 유효하지 않은 단과대에 대한 예외 처리 포함
3. **유저 조회 시 소속 정보 포함**
- `UserInfoResponse` DTO에 `college`, `department` 필드 추가
- `from(User user)` 메서드에서 소속 정보도 포함하여 응답
4. **단과대 여부 필터링 조회 API 구현**
- `PublicFolderController.getColleges()` API에 `@RequestParam isCollege` 추가
- `CollegeRepository`에서 `findAllByCollegeTrue()`, `findAllByCollegeFalse()` …
> [Feat #58] 회원가입 시 소속 정보 기입 및 단과대 관련 API 추가

- src/main/java/gnu/capstone/G_Learn_E/domain/problem/repository/ProblemWorkbookMapRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/controller/SolveLogController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolvedWorkbookId.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/repository/SolveLogRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/repository/SolvedWorkbookRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/WorkbookUpdateProblemsRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/WorkbookUpdateRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/Workbook.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/enums/ExamType.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/enums/Semester.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
#61
- `WorkbookController`에 문제집 정보 및 문제 수정 API 추가
- `SolveLogService`에서 문제 비교 및 로그 재생성 로직 수정
- `SolvedWorkbookRepository`에 `EntityGraph`를 적용한 커스텀 조회 메서드 추가
- `WorkbookService`에 문제 수정 및 비교 로직 리팩토링
- 관련 DTO, Enum, Entity에 필드 및 메서드 추가
어떤 변경 사항이 있나요?
1. **문제집 정보 수정 API 추가**  
- `WorkbookController`에 `/api/workbook/{workbookId}` 엔드포인트로 PATCH 요청 시 `WorkbookUpdateRequest` 기반으로 문제집의 이름, 교수명, 시험 유형, 표지 이미지, 학년, 학기 정보를 수정하는 기능을 추가했습니다.
2. **문제집 문제 수정 API 추가 및 기존 풀이 로그 삭제 처리**  
- `WorkbookController`에 `/api/workbook/{workbookId}/problems` 엔드포인트로 PATCH 요청 시 문제 리스트를 수정할 수 있도록 기능을 추가했습니다. 수정 시 기존 문제 풀이 로그를 전부 삭제한 후 새롭게 등록된 문제로 문제집을 구성합니다.
3. **SolveLogService 로직 개선**  
- 문제와 기존 로그 간 비교를 통해 존재하지 않는 문제 로그는 새롭게 생성하는 로직(`findOrCreateAllSolveLog`)을 도입하였습니다.
- `updateSolveLog` 메서드는 기존의 `SolvedWorkbook` 기반에서 …
> [Feat #61] 문제집 정보 및 문제 수정 기능 구현

- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
- src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/response/ToStringResponse.java
- src/main/java/gnu/capstone/G_Learn_E/global/fastapi/service/FastApiService.java
- src/main/resources/application.yml
#64
- FastAPI의 Audio To Text 기능을 연동하는 메서드 `audioToStringRequest`가 `FastApiService`에 추가되었습니다.
- 기존 `PdfToStringResponse` 클래스가 `ToStringResponse`로 이름이 변경되면서 범용 응답 DTO로 개선되었습니다.
- application.yml 설정에서 오디오 파일 업로드를 위한 `multipart` 최대 용량이 확대되었습니다.
- 파일명도 `PdfToStringResponse.java`에서 `ToStringResponse.java`로 변경되었습니다.
어떤 변경 사항이 있나요?
1. `FastApiService` 클래스에 `audioToStringRequest(AudioToStringRequest request)` 메서드를 추가하여, FastAPI 서버의 오디오 인식 API와 연동하도록 구현하였습니다. Multipart 업로드 방식으로 오디오 파일을 전송하며, 응답을 `ToStringResponse`로 받아 텍스트로 변환된 결과를 리턴합니다. 오류 발생 시 로그를 남기고 예외를 던지도록 구성되었습니다.
2. 기존 `PdfToStringResponse` 클래스는 오직 PDF 변환 응답에만 특화되어 있었으나, 이를 `ToStringResponse`로 리네이밍하여 Audio 및 PDF 텍스트 추출 모두에 재사용 가능하도록 구조를 변경하였습니다.
3. FastAPI 요청 처리부에서 클래스명을 `PdfToStringResponse` → `ToStringResponse`로 전환함으로써 코드 일관성을 확보하고, 두 …
> [Feat #64] Audio To Text 기능 FastAPI와 연동

- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/repository/SolvedWorkbookRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/controller/UserController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/CollegeRanking.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/DepartmentRanking.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/request/UserInfoUpdateRequest.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/response/CollegeRankingPageResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/response/DepartmentRankingPageResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/response/UserRankingPageResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/response/UserStatisticsResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/entity/User.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/entity/UserLevelPolicy.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/repository/UserRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/user/service/UserService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
#63
- 문제집 풀이 후 경험치 지급 로직 추가 및 중복 풀이 시 경험치 감소 처리
- 유저별 풀이한 문제집 개수 count 로직 추가
- 유저 정보 전체 수정 API 추가
- 유저 통계 및 랭킹 조회 API (유저, 학과, 단과대) 구현
- 랭킹 관련 DTO 및 응답 객체 신설
- 유저 엔티티에 문제집 관련 통계 필드 추가 및 업데이트 로직 구현
어떤 변경 사항이 있나요?
1. **문제집 풀이 경험치 지급 로직 개선**
- `WorkbookController`의 채점 로직에서 유저가 이미 푼 문제집일 경우 적은 경험치(EXP_RESOLVE_PROBLEM)를 지급하고, 새로운 풀이일 경우 더 많은 경험치(EXP_SOLVE_PROBLEM)를 지급하도록 처리하였습니다.
2. **유저가 푼 문제집 개수 자동 업데이트**
- `SolveLogService` 내 `updateSolvedWorkbookCountByUser()` 메서드를 통해 유저가 완료한 문제집 개수를 계산하여 `User` 엔티티의 `solvedWorkbookCount` 필드를 업데이트합니다.
3. **유저 정보 전체 수정 API 구현**
- `/api/user [PATCH]` 경로를 통해 이름, 닉네임, 단과대, 학과 정보를 한 번에 수정할 수 있는 API가 추가되었습니다.
4. **유저 통계 조회 API 추가**
- `/api/user/solving-statistics`에서 유저의 랭킹, 생성한 문제집 수, 푼 문제집 수를 조회할 수 있는 API가 구현되었습니다.
5. **유저 랭킹 조회 기능 구현**
- 유저, 학과, 단과대 랭킹 조회를 위한 …
> [Feat #63] 유저 통계 및 랭킹 API, 경험치 지급 로직 개선 및 유저 정보 수정 기능 추가

- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/controller/PublicFolderController.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/WorkbookResponse.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectWorkbookMapRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/service/PublicFolderService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/DownloadedWorkbookMap.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/repository/DownloadedWorkbookMapRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/repository/WorkbookRepository.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/DownloadedWorkbookService.java
- src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
#72
- 공개 문제집 목록 조회 API 구현 (전체/단과대/학과/과목 기준)
- 사용자가 다운로드한 문제집 여부 반환 로직 추가
- 다운로드 기록 엔티티 및 테이블 정의
- 다운로드 시 기록 저장 로직 추가
- 페이지네이션 및 정렬 기능 추가 지원
- API 반환값 포맷 개선
어떤 변경 사항이 있나요?
1. **공개 문제집 조회 API 구현**
- 전체/단과대/학과/과목 기준으로 문제집을 필터링하여 조회하는 기능 추가.
- 페이징, 정렬(order, sort) 파라미터를 통해 사용자 편의성 확보.
2. **다운로드 여부 표시 기능**
- 각 문제집이 사용자가 이미 다운로드한 항목인지 여부를 포함한 `WorkbookResponse` 리팩토링.
- 클라이언트 측에서 사용성 향상을 위한 UI 구현 가능성 제공.
3. **다운로드 기록 엔티티 및 테이블 추가**
- `DownloadedWorkbookMap` 엔티티 정의 및 `user_id`, `workbook_id` 복합 유니크 제약 설정.
- 다운로드 시점 기록(`downloaded_at`) 자동 생성.
4. **다운로드 시 기록 저장 로직 반영**
- `WorkbookService.downloadWorkbook()` 메서드 내부에서 다운로드 기록 저장 로직 삽입.
5. **페이징 및 정렬 기능 유효성 검사 추가**
- `PublicFolderService` 내 `getPageable()` 유틸 메서드 구현을 통해 잘못된 값에 대한 예외 처리 수행.
6. **API 반환값 누락 및 조회 오류 수정**
- 기존 API에서 반환값 일부 누락 및 데이터 조회 문제 …
> [Feat #72] 공개 문제집 조회 API 및 다운로드 이력 기능 추가
